---
AllCops:
  Exclude:
    - tmp/**/*
    - gemfiles/*
  TargetRubyVersion: 2.5
  NewCops: enable

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - simple_contracts.gemspec
    - Gemfile
    - spec/**/*

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 300

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/AbcSize:
  Max: 35

Style/FormatString:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
